boron/routes/application.py
from flask import (
    Blueprint,
    abort,
    render_template,
    request,
    redirect,
    url_for,
    make_response,
    Response,
)
from loguru import logger
from boron.util.authenticator import get_dev
from boron.util.db import query
from boron.util.apputil import (
    select_app,
    delete_application,
    get_app_users,
    get_app_keys,
    gen_keys,
    get_securedata,
    edit_securedata,
    create_securedata,
    delete_securedata,
    delete_key,
    update_key,
)

application = Blueprint("application", __name__, url_prefix="/applications/")


@application.get("home")
def dev_home() -> Response:
    dev = get_dev()

    apps = query(
        "SELECT * FROM applications WHERE dev_id = :dev_id", {"dev_id": dev.id}
    )

    return render_template("panel/panel_home.html", dev=dev, apps=apps)


# Create app (post)
@application.post("create")
def create_app() -> Response:
    """
    Form args:
    appname
    """
    dev = get_dev()

    appName = request.form.get("appname")
    if not appName:
        abort(400)

    query(
        "INSERT INTO applications (dev_id, name) VALUES (:dev_id, :name)",
        {"dev_id": dev.id, "name": appName},
    )

    logger.info(f"{dev.email} created app '{appName}'")

    return make_response(redirect(url_for("application.dev_home")))


# Delete app (post)
@application.post("<int:appid>/delete")
def delete_app(appid: int) -> Response:
    dev = get_dev()

    delete_application(dev, appid)

    return make_response(redirect(url_for("application.dev_home")))


# App home page
@application.get("<int:appid>/view")
def get_app(appid: int) -> Response:
    dev = get_dev()

    app = select_app(dev, appid)

    return render_template(
        "panel/app/app_home.html",
        dev=dev,
        app=app,
        navbar="app",
        sidebar="home",
    )


# App users page
@application.get("<appid>/users/")
def get_app_user(appid) -> Response:
    dev = get_dev()

    app = select_app(dev, appid)

    return render_template(
        "panel/app/users.html",
        dev=dev,
        app=app,
        users=get_app_users(dev, appid),
        navbar="app",
        sidebar="user",
    )


# App keys page
@application.get("<int:appid>/keys/")
def get_app_key(appid) -> Response:
    dev = get_dev()

    keys = get_app_keys(dev, appid)

    return render_template(
        "panel/app/keys.html",
        dev=dev,
        keys=keys,
        app=select_app(dev, appid),
        navbar="app",
        sidebar="key",
    )


@application.post("<int:appid>/keys")
def post_app_key(appid) -> Response:
    dev = get_dev()
    form = request.form
    try:
        count, length, prefix = (
            int(form.get("count")),
            int(form.get("length")),
            "".join(form.get("prefix").split()),
        )
        if not prefix:
            prefix = "BORON"
        prefix = f"{prefix}XXXXX"[:5]
    except Exception:
        return abort(400)
    gen_keys(dev, appid, count, length, prefix)
    return redirect(url_for("application.get_app_key", appid=appid))


@application.post("<int:appid>/keys/<int:keyid>/update")
def update_app_key(appid, keyid) -> Response:
    dev = get_dev()
    form = request.form
    used = form.get("used")
    used = used is not None
    update_key(dev, appid, keyid, {"used": used})
    return redirect(url_for("application.get_app_key", appid=appid))


@application.post("<int:appid>/keys/<int:keyid>/delete")
def delete_app_key(appid, keyid) -> Response:
    dev = get_dev()
    delete_key(dev, appid, keyid)
    return redirect(url_for("application.get_app_key", appid=appid))


@application.get("<int:appid>/data")
def get_data(appid) -> Response:
    dev = get_dev()
    return render_template(
        "panel/app/data.html",
        dev=dev,
        app=select_app(dev, appid),
        data=get_securedata(dev, appid),
        navbar="app",
        sidebar="data",
    )


@application.post("<int:appid>/data/create")
def create_data(appid) -> Response:
    keyname = request.form.get("key")

    create_securedata(keyname, get_dev(), appid)

    return make_response(redirect(url_for("application.get_data", appid=appid)))


@application.post("<int:appid>/data/edit")
def edit_data(appid) -> Response:
    keyid = request.form.get("id")
    keyname = request.form.get("key")
    keyvalue = request.form.get("value")

    edit_securedata(keyid, keyname, keyvalue, get_dev(), appid)

    return make_response(redirect(url_for("application.get_data", appid=appid)))


@application.post("<int:appid>/data/delete")
def delete_data(appid) -> Response:
    keyid = request.form.get("id")

    delete_securedata(keyid, get_dev(), appid)

    return make_response(redirect(url_for("application.get_data", appid=appid)))


# @application.context_processor
# def populate_ctx():
#    return {
# get user info
# request.cookies.get('session')
#    }

boron/routes/auth.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    make_response,
)
from loguru import logger
from boron.util.authenticator import (
    login as lgn,
    logout as lgo,
    get_dev,
    logged_in,
    register,
    abort,
)
from email.utils import parseaddr

auth = Blueprint("auth", __name__, url_prefix="/auth/")


@auth.get("register")
def get_register():
    return render_template("/auth/register.html")


@auth.post("register")
def post_register():
    try:
        form = request.form
        email = form.get("email")
        password = form.get("pass")
        assert parseaddr(email) != ("", "")
    except Exception:
        return abort(400)
    res = register(email, password)
    if res is not None:
        return render_template("/auth/register.html", error=res)
    return redirect(url_for("auth.get_login"))


@auth.get("login")
def get_login():
    if logged_in():
        return redirect(url_for("application.dev_home"))
    return render_template("/auth/login.html")


@auth.post("login")
def login():
    """
    email
    pass

    make error field to display in login form
    """

    e, p = request.form.get("email"), request.form.get("pass")
    logger.trace(f"{request.remote_addr} trying to login {e} with password = '{p}'")
    resp = lgn(e, p)

    if not resp["success"]:  # there was an error
        return render_template("/auth/login.html", error=resp["message"])

    response = make_response(redirect(url_for("application.dev_home")))
    response.set_cookie("session", resp["session"], max_age=3600)

    return response


@auth.route("logout")
def logout():
    dev = get_dev()
    logger.info(f"{dev.email} logged out session {dev.session}")
    lgo(dev.session)
    return make_response(redirect("/"))

boron/templates/base.html
<!DOCTYPE html>
<html lang="en" class="bg-stone-800 m-4">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{{ url_for('static', filename='boron.svg') }}" type="image/x-icon" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" />
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}

    {% endblock %}
  </head>

  <body class="select-none">
    <!-- Navbar -->
    {% if dev is defined %}
      <nav>
        <div class="mx-auto px-2 sm:px-6 lg:px-8">
          <div class="relative flex h-16 items-center justify-between">
            <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
              <a href="/" class="flex flex-shrink-0 items-center"><img class="h-8 w-auto" src="{{ url_for('static', filename='boron.svg') }}" alt="Fig. Boron" /></a>
              <div class="hidden sm:ml-6 sm:block">
                <div class="flex space-x-4">
                  <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-stone-600 hover:text-white" -->
                  <a href="{{ url_for('application.dev_home') }}" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-stone-600 hover:text-white {% if navbar is not defined or navbar == 'dash' %}bg-stone-900 text-white{% endif %}" aria-current="page">Dashboard</a>
                  <a href="#app" class="rounded-md px-3 py-2 text-sm font-medium text-gray-300 hover:bg-stone-600 hover:text-white {% if navbar == 'app' %}bg-stone-900 text-white{% endif %}">Application</a>
                </div>
              </div>
            </div>
            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
              <!-- Profile dropdown -->
              <div class="relative ml-3">
                <div>
                  <button id="user-dropdown-btn" type="button" onclick="reveal('#user-dropdown')" class="relative flex rounded-full bg-stone-600 text-sm" aria-expanded="false" aria-haspopup="true">
                    <svg width="40px" height="40px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <circle cx="12" cy="8" r="4" fill="#44403c" />
                      <path fill-rule="evenodd" clip-rule="evenodd" d="M12 13C8.33033 13 5.32016 15.4204 5.02395 18.5004C4.99752 18.7753 5.22389 19 5.50003 19H18.5C18.7762 19 19.0025 18.7753 18.9761 18.5004C18.6799 15.4204 15.6697 13 12 13Z" fill="#9333ea" />
                    </svg>
                  </button>
                </div>
                <div id="user-dropdown" class="hidden absolute right-0 z-10 m-4 w-48 origin-top-right rounded-md bg-stone-200 py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                  <!-- Active: "bg-gray-100", Not Active: "" -->
                  <a href="#" class="mx-1 block rounded-lg px-4 py-2 text-sm text-stone-800 hover:bg-stone-600 hover:text-white" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
                  <a href="#" class="mx-1 block rounded-lg px-4 py-2 text-sm text-stone-800 hover:bg-stone-600 hover:text-white" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                  <a href="{{ url_for('auth.logout') }}" class="mx-1 block rounded-lg px-4 py-2 text-sm text-stone-800 hover:bg-stone-600 hover:text-white" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>
    {% endif %}

    <!-- Sidebar -->
    {% if app is defined %}
      <hr class="flex h-1 rounded-full border-none bg-stone-700" />
      <!-- Sidebar -->
      <aside class="flex fixed top-16 mt-8 m-4 left-0 w-auto bottom-16" aria-label="Sidebar">
        <div class="rounded-lg h-full px-3 py-4 overflow-y-auto bg-stone-700">
          <ul class="space-y-2 font-medium text-white">
            <li>
              <a href="{{ url_for('application.get_app', appid=app.id) }}" class="flex items-center p-2 rounded-lg hover:bg-stone-600 {% if sidebar == 'home' %}bg-stone-800{% endif %}">
                <svg width="24px" height="24px" viewBox="0 -0.5 17 17">
                  <g id="SVGRepo_iconCarrier">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" style="--darkreader-inline-stroke: none;" data-darkreader-inline-stroke="">
                      <g transform="translate(1.000000, 1.000000)" fill="#a8a29e" style="--darkreader-inline-fill: #323739;" data-darkreader-inline-fill="">
                        <path d="M15.794,7.77 L11.984,3.864 L11.9839997,1.01706251 L11.0159997,1.03906251 L11.016,2.767 L8.502,0.245 C8.224,-0.031 7.776,-0.031 7.499,0.245 L0.206,7.771 C-0.069,8.048 -0.068,8.498 0.206,8.773 C0.482,9.049 0.933,9.049 1.209,8.772 L8,1.982 L14.793,8.772 C14.931,8.91 15.111,8.98 15.293,8.98 C15.474,8.98 15.654,8.912 15.794,8.773 C16.068,8.496 16.068,8.045 15.794,7.77 L15.794,7.77 Z" class="si-glyph-fill"></path> <path d="M3.043,8.532 L3.043,14.222 C3.043,14.616 3.26102394,15.0078125 3.61002394,15.0078125 L5.88702394,15.0078125 L5.95099996,11.0147705 L10.0249632,11.0147705 L10.0230128,15.0078125 L12.3260496,15.0078125 C12.6750496,15.0078125 12.958,14.617 12.958,14.222 L12.958,8.531 L8,3.625 L3.043,8.532 L3.043,8.532 Z" class="si-glyph-fill"></path>
                      </g>
                    </g>
                  </g>
                </svg>
                <span class="ms-3">App Home</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('application.get_app_user', appid=app.id) }}" class="flex items-center p-2 rounded-lg hover:bg-stone-600 {% if sidebar == 'user' %}bg-stone-800{% endif %}">
                <svg width="24px" height="24px" viewBox="0 0 24 24">
                  <g>
                    <path d="M1.5 6.5C1.5 3.46243 3.96243 1 7 1C10.0376 1 12.5 3.46243 12.5 6.5C12.5 9.53757 10.0376 12 7 12C3.96243 12 1.5 9.53757 1.5 6.5Z" fill="#a8a29e" style="--darkreader-inline-fill: #4c5255;" data-darkreader-inline-fill=""></path>
                    <path d="M14.4999 6.5C14.4999 8.00034 14.0593 9.39779 13.3005 10.57C14.2774 11.4585 15.5754 12 16.9999 12C20.0375 12 22.4999 9.53757 22.4999 6.5C22.4999 3.46243 20.0375 1 16.9999 1C15.5754 1 14.2774 1.54153 13.3005 2.42996C14.0593 3.60221 14.4999 4.99966 14.4999 6.5Z" fill="#a8a29e" style="--darkreader-inline-fill: #4c5255;" data-darkreader-inline-fill=""></path>
                    <path d="M0 18C0 15.7909 1.79086 14 4 14H10C12.2091 14 14 15.7909 14 18V22C14 22.5523 13.5523 23 13 23H1C0.447716 23 0 22.5523 0 22V18Z" fill="#a8a29e" style="--darkreader-inline-fill: #4c5255;" data-darkreader-inline-fill=""></path>
                    <path d="M16 18V23H23C23.5522 23 24 22.5523 24 22V18C24 15.7909 22.2091 14 20 14H14.4722C15.4222 15.0615 16 16.4633 16 18Z" fill="#a8a29e" style="--darkreader-inline-fill: #4c5255;" data-darkreader-inline-fill=""></path>
                  </g>
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Users</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('application.get_app_key', appid=app.id) }}" class="flex items-center p-2 rounded-lg hover:bg-stone-600 {% if sidebar == 'key' %}bg-stone-800{% endif %}">
                <svg width="24px" height="24px" viewBox="2 2 20 20">
                  <g>
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M18.9771 14.7904C21.6743 12.0932 21.6743 7.72013 18.9771 5.02291C16.2799 2.3257 11.9068 2.3257 9.20961 5.02291C7.41866 6.81385 6.8169 9.34366 7.40432 11.6311C7.49906 12 7.41492 12.399 7.14558 12.6684L3.43349 16.3804C3.11558 16.6984 2.95941 17.1435 3.00906 17.5904L3.24113 19.679C3.26587 19.9017 3.36566 20.1093 3.52408 20.2677L3.73229 20.4759C3.89072 20.6343 4.09834 20.7341 4.32101 20.7589L6.4096 20.9909C6.85645 21.0406 7.30164 20.8844 7.61956 20.5665L8.32958 19.8565L6.58343 18.1294C6.28893 17.8382 6.28632 17.3633 6.5776 17.0688C6.86888 16.7743 7.34375 16.7717 7.63825 17.063L9.39026 18.7958L11.3319 16.8541C11.6013 16.5848 12 16.5009 12.3689 16.5957C14.6563 17.1831 17.1861 16.5813 18.9771 14.7904ZM12.5858 8.58579C13.3668 7.80474 14.6332 7.80474 15.4142 8.58579C16.1953 9.36684 16.1953 10.6332 15.4142 11.4142C14.6332 12.1953 13.3668 12.1953 12.5858 11.4142C11.8047 10.6332 11.8047 9.36684 12.5858 8.58579Z" fill="#a8a29e"></path>
                  </g>
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Keys</span>
              </a>
            </li>
            <li>
              <a href="{{ url_for('application.get_data', appid=app.id) }}" class="flex items-center p-2 rounded-lg hover:bg-stone-600 {% if sidebar == 'data' %}bg-stone-800{% endif %}">
                <svg width="24px" height="24px" viewBox="0 -0.5 17 17">
                  <g transform="translate(1.000000, 1.000000)" fill="#a8a29e">
                    <path d="M11.988,8.031 L11.988,7 L4.031,7 L4.031,8.031 L1.938,8.031 L1.938,7 L0.0139770486,7 L0.0139770486,13 L16,13 L16,7 L14.031,7 L14.031,8.031 L11.988,8.031 Z" class="si-glyph-fill"></path> <path d="M4,4.9855957 L4,5.96789551 L12,5.96789551 L12,4.9855957 L14,4.9855957 L14,5.96789551 L15.9873047,5.96789551 L15.9873045,3 L0,3 L2.21252548e-07,5.96789551 L1.97381592,5.96789551 L1.97381606,4.9855957 L4,4.9855957 Z" class="si-glyph-fill"></path> <path d="M6.0029298,1.943 L5.01,1.943 L5.01,0.031 L10.969,0.031 L10.969,1.94299991 L10.0092771,1.94299994 L10.009277,0.986999997 L6.0029297,0.98699997 L6.0029298,1.943 Z" class="si-glyph-fill"></path>
                  </g>
                </svg>
                <span class="flex-1 ms-3 whitespace-nowrap">Secured Data</span>
              </a>
            </li>
          </ul>
        </div>
      </aside>
      <style>
        .body {
          position: fixed;
          margin: 1rem;
          left: 12rem;
          right: 0.5rem /* 8px */;
          top: 4rem;
          bottom: 0.5rem /* 8px */;
          margin-top: 2rem;
        }
      </style>
    {% endif %}

    <div class="body text-white select-text overflow-auto">
      {% block body %}

      {% endblock %}
    </div>
  </body>
  <script src="{{ url_for('static', filename='js/util.js') }}"></script>
</html>

boron/templates/httperr.html
{% extends 'base.html' %}
{% block head %}
  <title>{{ code }} {{ msg }}</title>
{% endblock %}
{% block body %}
  <div class="flex justify-center text-white">
    <section>
      <h1 class="text-4xl font-bold">{{ code }} {{ msg }}</h1>
      <p class="mt-8">
        <a href="{% if url is defined %}
            {{ url }}
          {% else %}
            {{ 'https://http.cat/status/%d'|format(code) }}
          {% endif %}">
          <img src="https://http.cat/{{ code }}" alt="Fig. http.cat/{{ code }}" />
        </a>
      </p>
    </section>
  </div>
{% endblock %}

boron/templates/index.html
{% extends 'base.html' %}
{% block head %}
  <title>Boron: License Key Management System</title>
{% endblock %}
{% block body %}

{% endblock %}