boron/routes/application.py
from flask import (
    Blueprint,
    abort,
    render_template,
    request,
    redirect,
    url_for,
    make_response,
    Response,
)
from loguru import logger
from boron.util.authenticator import get_dev
from boron.util.db import query
from boron.util.apputil import (
    select_app,
    delete_application,
    get_app_users,
    get_app_keys,
    gen_keys,
    get_securedata,
    edit_securedata,
    create_securedata,
    delete_securedata,
    delete_key,
    update_key,
)

application = Blueprint("application", __name__, url_prefix="/applications/")


@application.get("home")
def dev_home() -> Response:
    dev = get_dev()

    apps = query(
        "SELECT * FROM applications WHERE dev_id = :dev_id", {"dev_id": dev.id}
    )

    return render_template("panel/panel_home.html", dev=dev, apps=apps)


# Create app (post)
@application.post("create")
def create_app() -> Response:
    """
    Form args:
    appname
    """
    dev = get_dev()

    appName = request.form.get("appname")
    if not appName:
        abort(400)

    query(
        "INSERT INTO applications (dev_id, name) VALUES (:dev_id, :name)",
        {"dev_id": dev.id, "name": appName},
    )

    logger.info(f"{dev.email} created app '{appName}'")

    return make_response(redirect(url_for("application.dev_home")))


# Delete app (post)
@application.post("<int:appid>/delete")
def delete_app(appid: int) -> Response:
    dev = get_dev()

    delete_application(dev, appid)

    return make_response(redirect(url_for("application.dev_home")))


# App home page
@application.get("<int:appid>/view")
def get_app(appid: int) -> Response:
    dev = get_dev()

    app = select_app(dev, appid)

    return render_template(
        "panel/app/app_home.html",
        dev=dev,
        app=app,
        navbar="app",
        sidebar="home",
    )


# App users page
@application.get("<appid>/users/")
def get_app_user(appid) -> Response:
    dev = get_dev()

    app = select_app(dev, appid)

    return render_template(
        "panel/app/users.html",
        dev=dev,
        app=app,
        users=get_app_users(dev, appid),
        navbar="app",
        sidebar="user",
    )


# App keys page
@application.get("<int:appid>/keys/")
def get_app_key(appid) -> Response:
    dev = get_dev()

    keys = get_app_keys(dev, appid)

    return render_template(
        "panel/app/keys.html",
        dev=dev,
        keys=keys,
        app=select_app(dev, appid),
        navbar="app",
        sidebar="key",
    )


@application.post("<int:appid>/keys")
def post_app_key(appid) -> Response:
    dev = get_dev()
    form = request.form
    try:
        count, length, prefix = (
            int(form.get("count")),
            int(form.get("length")),
            "".join(form.get("prefix").split()),
        )
        if not prefix:
            prefix = "BORON"
        prefix = f"{prefix}XXXXX"[:5]
    except Exception:
        return abort(400)
    gen_keys(dev, appid, count, length, prefix)
    return redirect(url_for("application.get_app_key", appid=appid))


@application.post("<int:appid>/keys/<int:keyid>/update")
def update_app_key(appid, keyid) -> Response:
    dev = get_dev()
    form = request.form
    used = form.get("used")
    used = used is not None
    update_key(dev, appid, keyid, {"used": used})
    return redirect(url_for("application.get_app_key", appid=appid))


@application.post("<int:appid>/keys/<int:keyid>/delete")
def delete_app_key(appid, keyid) -> Response:
    dev = get_dev()
    delete_key(dev, appid, keyid)
    return redirect(url_for("application.get_app_key", appid=appid))


@application.get("<int:appid>/data")
def get_data(appid) -> Response:
    dev = get_dev()
    return render_template(
        "panel/app/data.html",
        dev=dev,
        app=select_app(dev, appid),
        data=get_securedata(dev, appid),
        navbar="app",
        sidebar="data",
    )


@application.post("<int:appid>/data/create")
def create_data(appid) -> Response:
    keyname = request.form.get("key")

    create_securedata(keyname, get_dev(), appid)

    return make_response(redirect(url_for("application.get_data", appid=appid)))


@application.post("<int:appid>/data/edit")
def edit_data(appid) -> Response:
    keyid = request.form.get("id")
    keyname = request.form.get("key")
    keyvalue = request.form.get("value")

    edit_securedata(keyid, keyname, keyvalue, get_dev(), appid)

    return make_response(redirect(url_for("application.get_data", appid=appid)))


@application.post("<int:appid>/data/delete")
def delete_data(appid) -> Response:
    keyid = request.form.get("id")

    delete_securedata(keyid, get_dev(), appid)

    return make_response(redirect(url_for("application.get_data", appid=appid)))


# @application.context_processor
# def populate_ctx():
#    return {
# get user info
# request.cookies.get('session')
#    }

boron/templates/panel/app/app_home.html
{% extends 'base.html' %}
{% block head %}
  <title>App: {{ app.name }}</title>
{% endblock %}
{% block body %}
  <div class="grid grid-cols-3 gap-4 m-4">
    <div class="bg-stone-700 rounded-3xl p-8">
      <dt>
        <h3 class="text-2xl font-bold">Users</h3>
      </dt>
      <dd><code class="text-4xl t-accent font-bold">{{ app.user_cnt }}</code></dd>
    </div>
    <div class="bg-stone-700 rounded-3xl p-8">
      <dt>
        <h3 class="text-2xl font-bold">Keys</h3>
      </dt>
      <dd><code class="text-4xl t-accent font-bold">{{ app.key_cnt }}</code></dd>
    </div>
    <div class="bg-stone-700 rounded-3xl p-8">
      <dt>
        <h3 class="text-2xl font-bold">Secured Data</h3>
      </dt>
      <dd><code class="text-4xl t-accent font-bold">{{ app.data_cnt }}</code></dd>
    </div>
  </div>
{% endblock %}

boron/templates/panel/app/data.html
{% extends 'base.html' %}
{% block head %}
<title>Secured Data - App: {{ app.name }}</title>
{% endblock %}
{% block body %}
<div class="flex p-4 mx-auto">
  <div class="sm:text-lg w-full">
    <section>
      <h2 class="mb-8 text-4xl tracking-tight font-bold text-white">
        Secure Data
        <button type="button" class="bg-none align-bottom" onclick="reveal('#create-data')">
          <svg width="48px" height="48x" viewBox="0 0 24 24">
            <g stroke-width="0" transform="translate(6,6), scale(0.5)">
              <rect x="-2.4" y="-2.4" width="28.80" height="28.80" rx="14.4" fill="#ffffff" strokewidth="0"
                style="--darkreader-inline-fill: #181a1b;" data-darkreader-inline-fill="" />
            </g>
            <g>
              <path fill-rule="evenodd" clip-rule="evenodd"
                d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22ZM12.75 9C12.75 8.58579 12.4142 8.25 12 8.25C11.5858 8.25 11.25 8.58579 11.25 9L11.25 11.25H9C8.58579 11.25 8.25 11.5858 8.25 12C8.25 12.4142 8.58579 12.75 9 12.75H11.25V15C11.25 15.4142 11.5858 15.75 12 15.75C12.4142 15.75 12.75 15.4142 12.75 15L12.75 12.75H15C15.4142 12.75 15.75 12.4142 15.75 12C15.75 11.5858 15.4142 11.25 15 11.25H12.75V9Z"
                fill="#9333ea" style="--darkreader-inline-fill: #6111a9;" data-darkreader-inline-fill="" />
            </g>
          </svg>
        </button>
      </h2>
      {% if data %}
      <div
        class="grid grid-flow-row gap-4 text-neutral-600 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {% for data in data %}
        <div class="w-full p-4 bg-stone-700 text-white shadow-lg rounded-lg">
          <div class="m-1">
            <section>
              <h3 class="text-3xl tracking-tight font-bold">
                <code>{{ data.key }}</code>
                <span class="text-sm font-normal">ID: {{ data.id }}</span>
              </h3>
              <code><textarea name="value" id="edit-value-input-{{ data.id }}" form="edit-data-{{ data.id }}" required rows="5" class="mt-2 resize-none block p-2 w-full text-sm rounded-lg border-none text-white bg-stone-800" spellcheck="false">{{ data.value }}</textarea></code>
            </section>
          </div>
          <div class="sm:flex sm:flex-row-reverse mt-4">
            <button type="button" onclick="reveal('#delete-data-{{ data.id }}')"
              class="mx-2 bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded-full">Delete</button>
            <button type="submit" form="edit-data-{{ data.id }}"
              class="mx-2 bg-emerald-500 hover:bg-emerald-700 text-white font-bold py-2 px-4 rounded-full">Apply</button>
          </div>
        </div>
        <form id="edit-data-{{ data.id }}" action="{{ url_for('application.edit_data', appid=app.id) }}" method="post"
          class="hidden">
          <input type="number" name="id" required value="{{ data.id }}" class="hidden" aria-hidden="true" />
          <input type="text" name="key" required value="{{ data.key }}" class="hidden" aria-hidden="true" />
        </form>
        <form id="delete-data-{{ data.id }}" class="hidden"
          action="{{ url_for('application.delete_data', appid=app.id) }}" method="post">
          <input name="id" value="{{ data.id }}" class="hidden" />
          <div class="relative z-10 text-white" aria-labelledby="modal-title" role="dialog" aria-modal="true">
            <div class="fixed inset-0 bg-stone-800 backdrop-blur bg-opacity-75 transition-opacity" aria-hidden="true">
            </div>
            <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
              <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
                <div
                  class="relative transform overflow-hidden rounded-lg bg-stone-600 text-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                  <div class="bg-stone-600 px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
                    <div class="sm:flex sm:items-start">
                      <div
                        class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
                        <svg class="h-6 w-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                          stroke="currentColor" aria-hidden="true">
                          <path stroke-linecap="round" stroke-linejoin="round"
                            d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                        </svg>
                      </div>
                      <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                        <h3 class="text-base font-semibold leading-6" id="modal-title">Secure-Data Deletion</h3>
                        <div class="mt-2">
                          <p class="text-sm">
                            Are you sure to delete <strong>{{ data.key }}</strong>?
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="bg-red-800 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
                    <button type="submit" form="delete-data-{{ data.id }}"
                      class="outline-none inline-flex w-full justify-center rounded-lg text-white bg-red-950 px-3 py-2 text-sm font-semibold shadow-sm hover:bg-red-900 sm:ml-3 sm:w-auto">Delete</button>
                    <button type="button" onclick="reveal('#delete-data-{{ data.id }}')"
                      class="b-btn mt-3 bg-white text-black shadow-sm hover:bg-stone-200 sm:mt-0 sm:w-auto">Cancel</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </form>
        {% endfor %}
      </div>
      {% else %}
      <div class="flex justify-center">
        <p class="text-stone-400">You do not have any stored secure data.</p>
      </div>
      {% endif %}
    </section>
  </div>
</div>

<div id="create-data" class="hidden relative z-10 text-white" aria-labelledby="modal-title" role="dialog"
  aria-modal="true">
  <form action="{{ url_for('application.create_data', appid=app.id) }}" method="post">
    <div class="fixed inset-0 bg-stone-800 backdrop-blur bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
      <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
        <div
          class="relative transform overflow-hidden rounded-lg bg-stone-600 text-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
          <div class="bg-stone-600 px-4 pb-4 pt-5 sm:p-6 sm:pb-4">
            <div class="sm:flex sm:items-start">
              <div
                class="mx-auto flex h-16 w-16 flex-shrink-0 items-center justify-center rounded-full bg-none sm:mx-0 sm:h-10 sm:w-10">
                <img class="h-12 w-auto" src="{{ url_for('static', filename='boron.svg') }}" alt="Fig. Boron" />
              </div>
              <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
                <h3 class="text-base font-semibold leading-6" id="modal-title">Create a Secure Data entry</h3>
                <div class="mt-2">
                  <div class="m-2 w-72">
                    <div class="relative w-full min-w-[200px] h-10">
                      <input name="key" required type="text" id="keyname-input" class="b-input"
                        placeholder="Enter a key name" />
                    </div>
                  </div>
                  <p class="text-sm">
                    The key name will be what you reference in your source code to get the accociated value. For
                    additional security, you can use a random value as the key.
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div class="bg-stone-800 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
            <button type="submit" class="b-btn shadow-sm sm:ml-3 sm:w-auto">Create</button>
            <button type="button" onclick="reveal('#create-data')"
              class="b-btn text-black bg-white hover:bg-stone-200 mt-3 shadow-sm sm:mt-0 sm:w-auto">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

boron/templates/panel/app/keys.html
{% extends 'base.html' %}
{% block head %}
  <title>Keys - App: {{ app.name }}</title>
{% endblock %}
{% block body %}
  <section>
    <form action="{{ url_for('application.post_app_key', appid=app.id) }}" method="post">
      <div class="m-2 grid grid-cols-4 gap-x-6 sm:grid-cols-8 text-white w-fit">
        <div class="col-span-2">
          <label for="count-input" class="block text-sm font-medium leading-6">Count</label>
          <input type="number" name="count" id="count-input" required class="b-input mt-1" value="10" />
        </div>

        <div class="col-span-2">
          <label for="length-input" class="block text-sm font-medium leading-6">Length</label>
          <input type="number" name="length" id="length-input" required class="b-input mt-1" value="10" />
        </div>

        <div class="col-span-2">
          <label for="prefix-input" class="block text-sm font-medium leading-6">Prefix</label>
          <input type="text" name="prefix" id="prefix-input" class="b-input mt-1" minlength="5" maxlength="5" placeholder="BORON" value="{{ (app.name|upper + 'XXXXX')|batch(5)|first|join }}" />
        </div>
        <button type="submit" class="b-btn col-span-1 w-fit m-2 mt-7 mb-0.5 px-2">Generate</button>
      </div>
    </form>
    {% if keys %}
      <div class="flex fixed flex-col top-48 m-2 mb-4 w-auto bottom-16">
        <div class="flex-grow overflow-auto">
          <table class="relative w-full">
            <thead class="bg-stone-900 sticky top-0 rounded-xl">
              <tr>
                <th class="px-8 p-1">ID</th>
                <th class="px-8 p-1">Key</th>
                <th class="px-8 p-1">Length</th>
                <th class="px-8 p-1">Creation Date</th>
                <th class="px-8 p-1">Used</th>
                <th class="px-8 p-1 select-none">Operation</th>
              </tr>
            </thead>
            <tbody class="overflow-scroll h-48 divide-y divide-solid divide-stone-700">
              {% for key in keys %}
                <tr>
                  <td class="px-8">{{ key.id }}</td>
                  <td class="px-8">
                    <code id="keyname-{{ key.id }}">{{ key.name }}</code>
                    <button type="button" onclick="toclipboard('#keyname-{{ key.id }}')">
                      <svg width="24px" height="24px" viewBox="0 0 24 18" class="-m-0.5">
                        <g id="SVGRepo_iconCarrier">
                          <path fill-rule="evenodd" clip-rule="evenodd" d="M19.5 16.5L19.5 4.5L18.75 3.75H9L8.25 4.5L8.25 7.5L5.25 7.5L4.5 8.25V20.25L5.25 21H15L15.75 20.25V17.25H18.75L19.5 16.5ZM15.75 15.75L15.75 8.25L15 7.5L9.75 7.5V5.25L18 5.25V15.75H15.75ZM6 9L14.25 9L14.25 19.5L6 19.5L6 9Z" fill="#ffffff"></path>
                        </g>
                      </svg>
                    </button>
                  </td>
                  <td class="px-8">{{ key.length }}</td>
                  <td class="px-8">
                    <script>
                      d = new Date('{{ key.creation }}')
                      document.write(d.toLocaleDateString())
                    </script>
                  </td>
                  <td class="px-8">
                    {% if key.used %}
                      <input type="checkbox" form="update-key-{{ key.id }}" name="used" checked />
                    {% else %}
                      <input type="checkbox" form="update-key-{{ key.id }}" name="used" />
                    {% endif %}
                  </td>
                  <td class="px-8 select-none">
                    <button type="submit" form="update-key-{{ key.id }}" class="mx-1 bg-emerald-500 hover:bg-emerald-700 text-white font-bold text-sm rounded-lg p-0.5">Update</button>
                    <button type="submit" form="delete-key-{{ key.id }}" class="mx-1 bg-red-500 hover:bg-red-700 text-white font-bold text-sm rounded-lg p-0.5">Delete</button>
                  </td>
                  <form id="update-key-{{ key.id }}" action="{{ url_for('application.update_app_key', appid=app.id, keyid=key.id) }}" method="post"></form>
                  <form id="delete-key-{{ key.id }}" action="{{ url_for('application.delete_app_key', appid=app.id, keyid=key.id) }}" method="post"></form>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    {% else %}
      <div class="flex justify-center mt-16">
        <p class="text-stone-400">There is currently no key for application {{ app.name }}.</p>
      </div>
    {% endif %}
  </section>
{% endblock %}

boron/templates/panel/app/users.html
{% extends 'base.html' %}
{% block head %}
  <title>Users - App: {{ app.name }}</title>
{% endblock %}
{% block body %}
  <section class="flex fixed flex-col top-24 m-2 mb-4 w-auto bottom-16">
    {% if users %}
      <div class="flex-grow overflow-auto">
        <table class="relative w-full p-2">
          <thead class="bg-stone-900 sticky top-0 rounded-xl">
            <tr>
              <th class="px-8 p-1">ID</th>
              <th class="px-8 p-1">Username</th>
              <th class="px-8 p-1">Expiration Date</th>
              <th class="px-8 p-1">Metadata</th>
              <th class="px-8 p-1">Logged in</th>
            </tr>
          </thead>
          <tbody class="overflow-scroll h-48 divide-y divide-solid divide-stone-700">
            {% for user in users %}
              <tr>
                <td class="px-8">{{ user.id }}</td>
                <td class="px-8">{{ user.username }}</td>
                <td class="px-8">
                  <script>
                    d = new Date('{{ user.expiration }}')
                    document.write(d.toLocaleDateString())
                    document.write(' ')
                    document.write(d.toLocaleTimeString())
                  </script>
                </td>
                <td class="px-8">
                  <code id="userdata-{{ user.id }}">{{ user.data }}</code>
                </td>
                <td class="px-8">
                  {% if user.session != '' %}
                    true
                  {% else %}
                    false
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="flex justify-center mt-16">
        <p class="text-stone-400">There is currently no user of the application {{ app.name }}.</p>
      </div>
    {% endif %}
  </section>
{% endblock %}